name: Run Telegram Bot

on:
  push:
    branches:
      - main
  
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Repositoriyni yuklab olish
        uses: actions/checkout@v3

      - name: 🛠 Python va kutubxonalarni o‘rnatish
        run: |
          sudo apt-get update
          
          pip install pyrogram tgcrypto

      - name: 🚀 Botni ishga tushirish
        run: python main.py
